### ISSUE TITLE
Tracking: Tools that use `@babel/core` as a dep

### ISSUE THREAD

**Issue by hzoo** [babel/babel-upgrade#20]
Writing down if tools are converted/what we need to do. Tracking date added to the list too.

- [x] Jest
  - https://github.com/facebook/jest#using-babel (`babel-core@^7.0.0-0`)
- [x] Ava
  - https://github.com/avajs/ava/issues/1598 Supported out of the box as of `1.0.0-beta.1`
- [ ] Gatsby https://github.com/gatsbyjs/gatsby/issues/3870 (Added 2/21)
- [x] Metro https://github.com/facebook/metro/issues/92 (Added 4/3)
- [x] react-native https://github.com/facebook/react-native/commit/f8d6b97140cffe8d18b2558f94570c8d1b410d5c

Apps
- [x] https://github.com/Automattic/wp-calypso/pull/23424 (Added 3/22)
- [ ] https://github.com/WordPress/gutenberg
- [ ] https://github.com/withspectrum/spectrum (Added 4/3)

**Comment by motss** [comment]
How about `ts-jest`?

**Comment by FND** [comment]
FWIW, I just upgraded [faucet-pipeline](http://faucet-pipeline.org) (https://github.com/faucet-pipeline/faucet-pipeline-js/pull/45), which turned out to be pleasantly straightforward once I'd figured out what needed to be done.

Just in case it helps improve the path for others, allow me to elaborate on my journey:

I didn't know babel-upgrade existed, only learned about it via [Henry's tweet](https://twitter.com/left_pad/status/981547260717752321). This brought me here - which was a little disorienting at first, as neither the issue description nor the README clearly state what babel-upgrade actually does. (Not a criticism, just an observation from someone who isn't tied into the community too closely.)

The usage instructions recommend using `npx babel-upgrade`, which I _thought_ meant I had to `npm install babel-upgrade` first (apparently npx does that on the fly; TIL!). The final step was inferring that babel-upgrade modifies the respective `package.json`, upgrading dependencies - for Babel's own packages as well as packages from the greater ecosystem (in my case: rollup-plugin-babel).

After that, everything was pretty simple: [updating dependencies](https://www.npmjs.com/package/npm-check-updates) to their latest version (babel-upgrade's transformations were a little outdated), running `npm install` (manually, mostly because I hadn't grokked babel-upgrade's role in the first place) and updating our tests (we're intentionally keeping a close eye on transpilation output, just to be safe).

The only trouble was figuring out the necessary Rollup adjustments (particularly WRT babel-plugin-external-helpers), but that wasn't a big deal either.

Anyway, looks like we're all set now - thanks for all your efforts!
