### ISSUE TITLE
Tracking: handling JavaScript files

### ISSUE THREAD

**Issue by hzoo** [babel/babel-upgrade#39]
We should use jscodeshift/babel-codemod for this.

- [ ] Upgrade a js config: `.babelrc.js`, `babel.config.js`, a preset written in JS, or a babel config written via `@babel/core` options or `babel-loader`.
- [ ] Upgrade any tools that use Babel directly
  - [ ] import statements like `babel-types` to `@babel/types`
  - [ ] API removals/deprecations/changes

**Comment by adityavohra7** [comment]
@hzoo mind if I take a stab at the "import statements like babel-types to @babel/types" part? 😄
